### PR TITLE
Now buildable through cargo + merge sort improvement

### PR DESCRIPTION
**Pull request by repi**
Set up so the repo can be built with cargo, e.g. with `cargo run` / `cargo build` / `cargo test`. The new main function in `main.rs` will call the `main` functions for all the sort functions. 

Could later replace the other main functions with #test functions in `main.rs` potentially instead.

Also ran the code through `cargo fmt` which runs [rustfmt](https://github.com/rust-lang-nursery/rustfmt) with default settings to follow the general Rust code standards, one can customise that one more also if one want with a `rustfmt.toml`, but would recommend just keeping it as standard for now while learning.

Finally I did some smaller improvements to the merge sort to allow it to use dynamic vectors instead of just fixed ones together with an optimisation/simplification of using `copy_from_slice` instead of manually looping through elements to copy

Enjoy :)

### CODE REVIEW

**Comment by repi** [comment]
Also threw in some more compact random number generation, using perhaps a bit more foreign but compact functional style in Rust. [link](https://github.com/zigguratvertigo/rust-sort/pull/1/commits/a2de00a9938031490305aa471e9177f5b410cf72)

**Review by zigguratvertigo — APPROVED** [review]
Great changes. Thanks!

When it comes to style, and I guess this is heavily influenced by the rust coding guidelines, not used to seeing the curly braces on the same line anymore. Not mandatory by the language actually, so I might bring those back to my own preference :P. We'll see. OK for now! :D

Thanks for the PR!

**Comment by zigguratvertigo** [comment]
Actually had to add:

`
**#![feature(rustc_private)]**

// Externals
**mod common;**
use common::{NUM_VALUES, MAX_RANGE, print_array};

**extern crate rand;**
use rand::distributions::{IndependentSample, Range};
`

For it to work on linux. Not needed for you I guess. Need to investigate why.

**Comment by zigguratvertigo** [comment]
In my case I launch directly from vscode.

**Pull request merged**
